//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись
    {
        public int IDЗаписи { get; set; }
        public int IDПользователя { get; set; }
        public int IDУслуги { get; set; }
        public string Телефон { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Время { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
